### ISSUE TITLE
AdminRoute to download stub file fails in subfolder

### ISSUE THREAD

**Issue by michael-wirth** [holomekc/wiremock#19]
The route mapping [AdminRoutes](https://github.com/holomekc/wiremock/blob/d6263e640a17197253e9dee4ab2d9af2647e7f65/src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L79) to download stub files doesn't support subfolders.

Request from the Wiremock UI fails with 404 error if it tries to download the stub file.
```bash
curl http://localhost/__admin/files/responses/account/bookings.json

> HTTP/1.1 404 Not Found
```

### Possible solution:
The mapping should support wildcards e.g. `router.add(GET, "/files/**", GetStubFilesTask.class);`
and use the request to extract the filename instead of using a path parameter in the GetStubFilesTask.

- [x] Which version of WireMock you're using -> 2.32.0.1-ui
- [x] How you're starting and configuring WireMock, including configuration or CLI the command line
  `docker run -d holomekc/wiremock-gui:2.32.0.1`
- [ ] A failing test case that demonstrates the problem
- [ ] Profiler data if the issue is performance related

**Comment by holomekc** [comment]
Is fixed in 2.32.0.2. Thank you for the feedback!
