### ISSUE TITLE
unable to access jarfile wiremock by docker-compse

### ISSUE THREAD

**Issue by NewbieProger** [holomekc/wiremock#22]
Hello. When I using docker compose we need to volume mappings. 
With ur project i cant do that

When i try it with this compose

> wiremock:
>     image: holomekc/wiremock-gui:latest
>     container_name: wiremock
>     healthcheck:
>       test: "[ $$(curl -s -o /dev/null -w \"%{http_code}\" localhost:52250/__admin/settings) = \"200\" ]"
>       interval: 10s
>       timeout: 1s
>       retries: 30
>     volumes:
>       - ./src/test/resources/testdata/stub:/home/wiremock
>     environment:
>       WIREMOCK_OPTIONS: "--port=52250,--verbose,--local-response-templating"

I got an error : unable to access jarfile wiremock

With wiremock/wiremock i dont have any troubles

**Comment by holomekc** [comment]
This happens because you overwrite the directory where the jar file is located. I currently do not use the same Dockerfile structure as wiremock/wiremock. Maybe I will change that in the future. Currently you need to do:

```yaml
    volumes:
      - ./src/test/resources/testdata/stub/mappings:/home/wiremock/mappings
      - ./src/test/resources/testdata/stub/__files:/home/wiremock/__files
```
