### ISSUE TITLE
gui doesn't reload fresh value after edit

### ISSUE THREAD

**Issue by roborobo2** [holomekc/wiremock#24]
## Bug reports

Hi, we have problem with wiremock gui. after editing or creating does not show latest changes. we must reload page to show stored latest data.

- [ ] Which version of WireMock you're using
- wiremock-gui:2.32.0.2

- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
-  --port=8080,--https-port=8433,--max-request-journal=1000,--global-response-templating,--verbose,--root-dir=/home/wiremock

- [ ] A failing test case that demonstrates the problem  

https://user-images.githubusercontent.com/2378631/166427005-a154325d-401f-4dc0-8cf6-4113bed5f872.mp4

**Comment by holomekc** [comment]
Hi. I cannot see that on my machine. Can you open the dev tools and in network check if the events websocket connection is looking fine. This is how it looks for me. The mappings event should be shown in case you edit something:
![image](https://user-images.githubusercontent.com/30546982/168425224-93a28d8d-e084-458a-a8ff-2f3b0af425ff.png)

**Comment by holomekc** [comment]
Hmm I can reproduce it now. I will take a look!

**Comment by holomekc** [comment]
Should be fixed in 2.33.2.1-ui . Build is still running. I changed a bit more. Rendering should be faster as well. In case you face any issues please let me know.

**Comment by roborobo2** [comment]
I have websocket errors in old and also in LATEST version
![image](https://user-images.githubusercontent.com/2378631/168783173-69846a19-b45d-4e33-8837-d6abec7caa0d.png)

In Firefox, latest wiremock change behavior. old version does not update view AFTER SAVE. latest version does not update view when I entering edit mode (edit window contains old values)

seems that Chrome use WSS protocol instead of WS and chrome works ok.

**Comment by holomekc** [comment]
I will check the behavior in firefox as soon i am back.. thx this helps. It may take a while though sorry.
