### ISSUE TITLE
Changing mapping file does not update the tabs different from the current one

### ISSUE THREAD

**Issue by lhimo** [holomekc/wiremock#25]
- WireMock version 2.33.2.1-ui
- running from docker with global response templating

**Repro steps**

1. Open a mapping from the folder view, the "Raw" tab shows info for this mapping
2. Move to the "Test" or "Separated" tab, the tab shows info for the same mapping
3. Change mapping file by clicking on a different one in the folder view, the current tab changes the reference as well
4. Move back to the "Raw" tab

**Expected result**

The tab information corresponds to the _currently_ selected mapping

**Actual result**

The tab information corresponds to the _previously_ selected mapping

**Comment by holomekc** [comment]
Hi,
Sorry for my inactivity. I will check this next weekend.
Br,
Christopher
