### ISSUE TITLE
How to change wiremock servlet url

### ISSUE THREAD

**Issue by tarteens** [holomekc/wiremock#26]
Hi,

I'm trying to deploy this docker image on my k8s cluster. I'm want to access the GUI behind http://ip:port/wiremock/__admin/webapp/ (instead of default http://ip:port/__admin/webapp)

I can't find the proper documentation to allow me to change the root servlet context. 

It this something that it possible ? 

Thanks for the help

**Comment by holomekc** [comment]
No this is not possible as far as I know with wiremock. But when you are running in k8s maybe adjust the ingress configuration to rewrite the path.
