### ISSUE TITLE
Duplicate stub mapping ID due to Kubernetes ConfigMap

### ISSUE THREAD

**Issue by jrs666666** [holomekc/wiremock#269]
After upgrading from wiremock-gui:3.6.26 to 3.7.1 I recognized a new curious error message during startup:
```
Defaulted container "wiremock" out of: wiremock, init-wiremock-extensions (init)
Exception in thread "main" com.github.tomakehurst.wiremock.common.InvalidInputException: {
  "errors" : [ {
    "code" : 109,
    "title" : "Duplicate stub mapping ID",
    "detail" : "ID of the provided stub mapping 'b224214f-7e0d-4363-9d41-dcc239e4a660' is already taken by another stub mapping"
  } ]
}
	at com.github.tomakehurst.wiremock.stubbing.AbstractStubMappings.addMapping(AbstractStubMappings.java:169)
	at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:139)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:301)
	at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:294)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:153)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:74)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:72)
	at wiremock.Run.main(Run.java:23)
```

I double-checked my Kubernetes ConfigMap which confirmed that I'm using unique UUIDs for my stub definitions. However, I recognized that mounting a directory at /home/wiremock/mappings using a ConfigMap provides this hierarchy:
```
root@wiremock-66dc8ccf9b-2z8m2:/home/wiremock/mappings# ls -laR
.:
total 0
drwxrwxrwx. 3 root root 152 Jul  5 13:51 .
drwxr-xr-x. 1 root root  25 Jul  5 13:52 ..
drwxr-xr-x. 2 root root  98 Jul  5 13:51 ..2024_07_05_13_51_53.2567708330
lrwxrwxrwx. 1 root root  32 Jul  5 13:51 ..data -> ..2024_07_05_13_51_53.2567708330
lrwxrwxrwx. 1 root root  23 Jul  5 13:51 jwks.json -> ..data/jwks.json
lrwxrwxrwx. 1 root root  31 Jul  5 13:51 webhook-test.json -> ..data/webhook-test.json

./..2024_07_05_13_51_53.2567708330:
total 12
drwxr-xr-x. 2 root root   98 Jul  5 13:51 .
drwxrwxrwx. 3 root root  152 Jul  5 13:51 ..
-rw-r--r--. 1 root root  264 Jul  5 13:51 jwks.json
-rw-r--r--. 1 root root  432 Jul  5 13:51 webhook-test.json
```

I assume some methods were improved and recursively traverse all sub directories while detecting "duplicates" of the same file. Or, soft-linked files were being ignored in the past.

Will there a possibility to disable the traversal of directories in future by any chance?

**Comment by holomekc** [comment]
Hmm I think this is due to:
https://github.com/wiremock/wiremock/issues/2734

I assume you would have the same behavior using the official wiremock docker image without my gui extension. At least I see no special handling, which would somehow skip the logic when adding mappings. See: https://github.com/wiremock/wiremock/blob/c91b71f4b652b41b375e9b5b10cd5050cb8a6131/src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractStubMappings.java#L160

Could you test this? If so I would say this should be handled by wiremock itself.

Br,
Chris

**Comment by jrs666666** [comment]
@holomekc Sorry for the late reply. You're totally right, the issue appears in 'wiremock/wiremock:3.8.0' as well.

I close this issue here, because it's already mentioned inside https://github.com/wiremock/wiremock/issues/2778
