### ISSUE TITLE
Can only POST when testing mapping

### ISSUE THREAD

**Issue by chauwel** [holomekc/wiremock#27]
Hi,

Apparently there is no way to specify the HTTP method when running a test.

Regards.

**Comment by holomekc** [comment]
Hi,
Sorry for my inactivity. I will check this next weekend.
Br,
Christopher

**Comment by holomekc** [comment]
You can overwrite the HTTP method now in the newest version: [2.34.0.0](https://hub.docker.com/layers/holomekc/wiremock-gui/2.34.0.0/images/sha256-ae8b713053689d44e1d9b1a7eed5c66e5b7726e04672d86ec85eec07435b75bb?context=explore)
