### ISSUE TITLE
Help: recording

### ISSUE THREAD

**Issue by NewbieProger** [holomekc/wiremock#29]
How can I use stateMachine recording in ur build via standalone parameters       WIREMOCK_OPTIONS? 

I set this one but it didn't help me

```
    environment:
      WIREMOCK_OPTIONS: "--port=52250,--local-response-templating,--verbose,--root-dir=/home/wiremock/storage,--record-mappings,--match-headers,--proxy-all='http://localhost:8180'"
```

**Comment by holomekc** [comment]
Hi,
Sorry for my inactivity. I will check this next weekend.
Br,
Christopher

**Comment by holomekc** [comment]
- You can record also via UI in the settings menu
- You can add the mapping to map every request manually
- I would recommend using the new approach to set the configuration. See readme.md
