### ISSUE TITLE
Support for Arm 

### ISSUE THREAD

**Issue by kasperg** [holomekc/wiremock#33]
I noticed that [`holomekc/wiremock-gui`](https://hub.docker.com/r/holomekc/wiremock-gui/) does not support Arm.

Are there any plans to provide Docker images for this architecture?

**Comment by holomekc** [comment]
New versioning in Docker:
holomekc/wiremock-gui:2.35.0.0 using ubuntu jammy which supports also arm
holomekc/wiremock-gui:2.35.0.0-alpine the usual alpine image. No support for arm

Also:
holomekc/wiremock-gui:latest
holomekc/wiremock-gui:latest-alpine

If you face any issues please let me know

**Comment by kasperg** [comment]
:+1: Thanks @holomekc !
