### ISSUE TITLE
Requirement: Can the docker restart reload the data into memory? 

### ISSUE THREAD

**Issue by cookie220** [holomekc/wiremock#34]
## Feature requests

As far as I know when the docker container restart or stop by some reason, the mock data seems release from the memory.
In this case, we have to import the data again into the wiremock server.

So please help reload the existing json file when docker container start or restart to avoid data missing or duplicate operations.

Thanks a lot!

**Comment by holomekc** [comment]
Hi,
do you save the mappings? Just importing them via HTTP is not enough. Also you can define a volume in your docker compose definition so that they are persistent even if you recreate the container.

**Comment by cookie220** [comment]
Thanks for for reply
