### ISSUE TITLE
Version 2.35.0.1 doesn't listen on https port

### ISSUE THREAD

**Issue by alexku7** [holomekc/wiremock#37]
Seems , starting from 2.35.0.1 something broken in https port.
The version 2.35.0.0 works correctly , but 2.35.0.1 doesn't listen  on https port :(

I set it by the following env:

`WIREMOCK_OPTIONS: "--https-port=9021,--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage"`

**Comment by blazp1337** [comment]
Looks like Wiremock is no longer accepting WIREMOCK_OPTIONS env var. https://github.com/holomekc/wiremock/commit/cc3098cc213c42e7a424663efee005de643b2fd9

**Comment by holomekc** [comment]
Sorry for the very late response. There was a breaking change:
https://github.com/holomekc/wiremock#breaking-change--23501
Also check the docker-compose example below. The reason for that is that I had a clash in the approach with WIREMOCK_OPTIONS and the variables feature of Wiremock. The docker-compose example contains both.

If it is still not working please reopen the issue.
