### ISSUE TITLE
Update to latest version of wiremock

### ISSUE THREAD

**Issue by craigmain** [holomekc/wiremock#42]
Hi,

Awesome interface BTW.
I really like what you've done, polished functional, and really useful.

What cadence do you use to keep up with wiremock releases?
It would be nice to have an update for wiremock.

It would also be really useful to have the wiremock version displayed somewhere on the UI.

`wiremock-standalone-3.3.1`

**Comment by holomekc** [comment]
Hi,

thx for the kind words. Mostly manual. I think there was never a version without a conflict to resolve during merge of the upstream. Most of the time because of the README.md 😂. I will check how I can include the version somehow. 

Sorry for the late answer. Too busy…

**Comment by holomekc** [comment]
3.3.1.0 is released. There are some bigger changes due to Angular 17. In case you face any issue, please let me know.
