### ISSUE TITLE
The save mapping feature generate not beautiful JSON

### ISSUE THREAD

**Issue by 2ur1st** [holomekc/wiremock#43]
After click on button "**Save Mappings**" the format of all JSON files have been change to not beautiful format
<img width="494" alt="Screenshot 2023-11-19 at 20 17 45" src="https://github.com/holomekc/wiremock/assets/4361999/88618ed6-eecc-478d-9cca-d913d81e2342">

**You can see spaces around colon**, How I can set only one space after colon?
Example:
```json
{
  "id" : "287ae1c0-eef7-4b1c-97dd-1cca558c2d14",
  "request" : {
    "urlPath": "/api/order",
    "method": "POST",
    "headers": {
      "Content-Type": {
        "equalTo": "application/x-www-form-urlencoded"
      }
    }
  },
  "response" : {
    "status" : 200,
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "body-transformer" ]
  },
  "uuid" : "287ae1c0-eef7-4b1c-97dd-1cca558c2d14",
  "persistent" : true,
  "priority" : 1,
  "metadata" : {
    "wiremock-gui" : {
      "folder" : "/order/create"
    }
  }
}
```

**Comment by holomekc** [comment]
Hi,

I will check that. I think I cannot really change that. I use the wiremock api to push the content and the actual json file is than written by wiremock, but I am not sure right now.  We will see.

thx for the feedback though.

**Comment by holomekc** [comment]
https://stackoverflow.com/questions/41508864/jackson-custom-serializer-json-format

**Comment by holomekc** [comment]
Hmm. I changed my mind. I would be forced to update some tests. In general that would not be an issue, but maybe it would be better to ask the wiremock project itself to "fix" that. See revert commit: https://github.com/holomekc/wiremock/commit/84e2d816155e433b75340f788e9676601aaee15d
