### ISSUE TITLE
Add file upload

### ISSUE THREAD

**Issue by bogdankorobka** [holomekc/wiremock#45]
Hello, the wiremock API has methods for downloading and deleting files. I didn't find such functionality in your application. Can you add?

https://github.com/wiremock/wiremock/blob/6b8656eaea3183befa8fd8a10e64c7eab520a205/src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java#L75

**Comment by holomekc** [comment]
Hi,
Thx for the idea. Can you explain your expectations a little bit. 
i think download is not a problem. I can extend the mappings page and enable or show a button in case the mapping has a file.

I am not sure regarding deleting files. Do you have a new view in mind to manage the files. Like list all files, select them and then remove them? Or do you mean on a selected mapping the option to do that? There I only know that a related file exist as long as the mapping definition has one

Furthermore, I guess upload would make sense as well?

Br,
Chris

**Comment by holomekc** [comment]
Hi @bogdankorobka,

you can test https://github.com/holomekc/wiremock/releases/tag/3.3.1.2-ui . If something is missing please reopen an let me know.

Br,
Chris

**Comment by bogdankorobka** [comment]
its good!!!
For me, a necessary feature is editing files. If you can do the editing from the form, it will be very good.

**Comment by holomekc** [comment]
Hi @bogdankorobka ,

Ok sure let me check.

Br,
Chris

**Comment by holomekc** [comment]
Hi @bogdankorobka ,

see 3.3.1.3. This was on short notice. If you face some issue please let me know.

Br,
Chris
