### ISSUE TITLE
Wiremock base url

### ISSUE THREAD

**Issue by josemarflausino** [holomekc/wiremock#50]
Hi, 

is it possible to change the env wiremockUrl?

**Comment by holomekc** [comment]
Hi @josemarflausino,
can you explain your question in more detail? Do you mean connecting to a different wiremock instance? Not at the moment. It is all bundles together in a standalone jar and available as docker image. Do you have a use-case in mind where this would be helpful?

Br,
Chris

**Comment by josemarflausino** [comment]
Hi @holomekc,

I was too quick to ask. It won't be necessary. I'm trying to create a common mock-server using k8s. Due my infrastructure configuration, I was facing redirect issues when accessing /__admin/webapp. But it's now clear to me that I need to check theses configurations. Sorry to bother and congrats on this project, it is very useful.

Thank You

**Comment by holomekc** [comment]
Hi @josemarflausino,
Thx for the kind words. Great to hear that everything is working fine and is helpful.

Have a great Christmas time.

Br,
Chris
