### ISSUE TITLE
500 when there are feilds with null value

### ISSUE THREAD

**Issue by SkyRaider56** [holomekc/wiremock#509]
![image](https://github.com/user-attachments/assets/9379fd5b-e4dd-4e41-99cd-234cad695a94)

BUT

When I change "cellularPhone": null -> "cellularPhone": []

![image](https://github.com/user-attachments/assets/3de37d97-2a36-45df-9d3e-f7ebf7611b21)

It gets OK

**Comment by SkyRaider56** [comment]
{
	"passportId": [
		"31f74c9f-b462-4612-9f0c-acaf3e20f244"
	],
	"crmClientNumber": null,
	"cellularPhone": null,
	"cellularPhoneConfirmed": true,
	"cellularPhoneNotNull": true
}

**Comment by holomekc** [comment]
Hi @SkyRaider56 ,
From your pictures it looks like you are using a mapping with jsonpath and you are using Insomnia. This does not sound like a wiremock-gui issue, but as a topic for wiremock itself. I did not check the wiremock docs. Maybe there are some infos to ensure null safety. If not I would recommend to create an issue in the wiremock repo.

Br
Chris
